version: "3"
services:
# VIRTUAL_HOST - используется для "рефлексии" через докер-апи для Nginx-proxy
# VIRTUAL_PORT и LETSENCRYPT_HOST - тоже  
  postgres:
    container_name: techradar-db
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - internal

  api:
    container_name: techradar-api
    image: techradarapi/techradar-api:${TAG:-release}
    environment:
      - VIRTUAL_HOST=${COMMON_DOMAIN}
      - LETSENCRYPT_HOST=${COMMON_DOMAIN}
      - VIRTUAL_PORT=8080
      - PORT=8080
    ports:
      - 80:8080
    depends_on:
      - postgres
    networks:
      - internal
      - reverse-proxy
  
  client:
    container_name: techradar-client
    image: techradarapi/techradar-api:TESTING
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=${COMMON_DOMAIN}
      - LETSENCRYPT_HOST=${COMMON_DOMAIN}
      - VIRTUAL_PORT=80
      - PORT=80
      - HOST=0.0.0.0
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
  internal:
    driver: bridge
volumes:
  postgres:
