version: "3"
services:
# VIRTUAL_HOST - используется для "рефлексии" через докер-апи для Nginx-proxy
# VIRTUAL_PORT и LETSENCRYPT_HOST - тоже  
  postgres:
    container_name: techradar-db
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - internal

  api:
    container_name: techradar-api
    image: techradarapi/techradar-api:${TAG:-release}
    environment:
      - VIRTUAL_HOST=${COMMON_DOMAIN}
      - LETSENCRYPT_HOST=${COMMON_DOMAIN}
    expose:
      - 8080
    depends_on:
      - postgres
    networks:
      - internal
      - reverse-proxy
  
  client:
    build:
      context: ${FRONTEND_SRC_DIR}
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=${COMMON_DOMAIN}
      - LETSENCRYPT_HOST=${COMMON_DOMAIN}
      - HOST=0.0.0.0
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  internal:
    driver: bridge
